/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SalesLeadsRouteImport } from './routes/sales-leads'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as VerificationQueueRouteImport } from './routes/verification-queue'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLeadsRoute = SalesLeadsRouteImport.update({
  id: '/sales-leads',
  path: '/sales-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationQueueRoute = VerificationQueueRouteImport.update({
  id: '/verification-queue',
  path: '/verification-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sales-leads': typeof SalesLeadsRoute
  '/triage': typeof TriageRoute
  '/verification-queue': typeof VerificationQueueRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sales-leads': typeof SalesLeadsRoute
  '/triage': typeof TriageRoute
  '/verification-queue': typeof VerificationQueueRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sales-leads': typeof SalesLeadsRoute
  '/triage': typeof TriageRoute
  '/verification-queue': typeof VerificationQueueRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sales-leads'
    | '/triage'
    | '/verification-queue'
    | '/tickets/$id'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sales-leads'
    | '/triage'
    | '/verification-queue'
    | '/tickets/$id'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sales-leads'
    | '/triage'
    | '/verification-queue'
    | '/tickets/$id'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SalesLeadsRoute: typeof SalesLeadsRoute
  TriageRoute: typeof TriageRoute
  VerificationQueueRoute: typeof VerificationQueueRoute
  TicketsIdRoute: typeof TicketsIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-leads': {
      id: '/sales-leads'
      path: '/sales-leads'
      fullPath: '/sales-leads'
      preLoaderRoute: typeof SalesLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-queue': {
      id: '/verification-queue'
      path: '/verification-queue'
      fullPath: '/verification-queue'
      preLoaderRoute: typeof VerificationQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SalesLeadsRoute: SalesLeadsRoute,
  TriageRoute: TriageRoute,
  VerificationQueueRoute: VerificationQueueRoute,
  TicketsIdRoute: TicketsIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
